server:
  port: 8881

spring:
  application:
      name: order-service
# reids
#  redis:
#    database: 0
#    host: 192.168.0.6
#    port: 6379
#    timeout: 2000ms


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.213:8761/eureka/

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule



feign:
  hystrix:
    enabled: true

  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000


#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000


management:
  endpoints:
    web:
      exposure:
        include: "*"